Repository swsnu/swpp2021-team8, pull requests merged in 2021-11, with the labels that each got.

#6 [Feature] Implement navbar and build up base CSS
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/base.scss
  frontend/src/components/base/NavBar.js
  frontend/src/components/base/NavBar.scss
  frontend/src/components/base/NavBar.test.js
  frontend/src/components/content/ContentListItem.js
  frontend/src/components/group/GroupListItem.js
  frontend/src/fonts/Josefin_Sans/JosefinSans-Italic-VariableFont_wght.ttf
  frontend/src/fonts/Josefin_Sans/JosefinSans-VariableFont_wght.ttf
  frontend/src/fonts/Josefin_Sans/OFL.txt
  frontend/src/fonts/Josefin_Sans/README.txt
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-Bold.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-BoldItalic.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-ExtraLight.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-ExtraLightItalic.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-Italic.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-Light.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-LightItalic.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-Medium.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-MediumItalic.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-Regular.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-SemiBold.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-SemiBoldItalic.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-Thin.ttf
  frontend/src/fonts/Josefin_Sans/static/JosefinSans-ThinItalic.ttf
  frontend/src/fonts/Roboto/LICENSE.txt
  frontend/src/fonts/Roboto/Roboto-Black.ttf
  frontend/src/fonts/Roboto/Roboto-BlackItalic.ttf
  frontend/src/fonts/Roboto/Roboto-Bold.ttf
  frontend/src/fonts/Roboto/Roboto-BoldItalic.ttf
  frontend/src/fonts/Roboto/Roboto-Italic.ttf
  frontend/src/fonts/Roboto/Roboto-Light.ttf
  frontend/src/fonts/Roboto/Roboto-LightItalic.ttf
  frontend/src/fonts/Roboto/Roboto-Medium.ttf
  frontend/src/fonts/Roboto/Roboto-MediumItalic.ttf
  frontend/src/fonts/Roboto/Roboto-Regular.ttf
  frontend/src/fonts/Roboto/Roboto-Thin.ttf
  frontend/src/fonts/Roboto/Roboto-ThinItalic.ttf
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/index.scss
  frontend/src/reset.scss
  frontend/src/setupTests.js
  frontend/src/store/AuthStore.js
  frontend/src/store/index.js
  frontend/yarn.lock
Labels: enhancement

#9 [Feature] Implement User, Group, Content, Review models & apis
  backend/backend/urls.py
  backend/ott_image/watcha_logo.jpeg
  backend/ott_image/watcha_logo_HSXCsT1.jpeg
  backend/subroker/admin.py
  backend/subroker/migrations/0001_initial.py
  backend/subroker/migrations/0002_auto_20211106_0840.py
  backend/subroker/migrations/0003_group.py
  backend/subroker/migrations/0004_content_review.py
  backend/subroker/migrations/0005_alter_content_user_id.py
  backend/subroker/migrations/0006_alter_group_members.py
  backend/subroker/migrations/__pycache__/0001_initial.cpython-39.pyc
  backend/subroker/migrations/__pycache__/0002_auto_20211106_0840.cpython-39.pyc
  backend/subroker/migrations/__pycache__/0003_group.cpython-39.pyc
  backend/subroker/migrations/__pycache__/0004_content_review.cpython-39.pyc
  backend/subroker/migrations/__pycache__/0005_alter_content_user_id.cpython-39.pyc
  backend/subroker/migrations/__pycache__/0006_alter_group_members.cpython-39.pyc
  backend/subroker/migrations/__pycache__/__init__.cpython-39.pyc
  backend/subroker/models.py
  backend/subroker/tests.py
  backend/subroker/urls.py
  backend/subroker/views.py
Labels: setup

#15 [Feature] Implement auth/login page
  .travis.yml
  README.md
  backend/backend/__pycache__/__init__.cpython-37.pyc
  backend/backend/__pycache__/settings.cpython-37.pyc
  backend/backend/__pycache__/urls.cpython-37.pyc
  backend/backend/__pycache__/wsgi.cpython-37.pyc
  backend/backend/settings.py
  backend/backend/urls.py
  backend/db.sqlite3
  backend/subroker/__pycache__/__init__.cpython-37.pyc
  backend/subroker/__pycache__/admin.cpython-37.pyc
  backend/subroker/__pycache__/apps.cpython-37.pyc
  backend/subroker/__pycache__/models.cpython-37.pyc
  backend/subroker/__pycache__/urls.cpython-37.pyc
  backend/subroker/__pycache__/views.cpython-37.pyc
  backend/subroker/admin.py
  backend/subroker/migrations/0002_delete_user.py
  backend/subroker/migrations/__pycache__/0001_initial.cpython-37.pyc
  backend/subroker/migrations/__pycache__/0002_delete_user.cpython-37.pyc
  backend/subroker/migrations/__pycache__/__init__.cpython-37.pyc
  backend/subroker/urls.py
  backend/subroker/views.py
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/base.scss
  frontend/src/containers/auth/LoginPage.js
  frontend/src/containers/auth/LoginPage.scss
  frontend/src/containers/auth/LoginPage.test.js
  frontend/src/containers/auth/SignUpPage.js
  frontend/src/containers/auth/SignUpPage.scss
  frontend/src/containers/auth/SignUpPage.test.js
  frontend/src/index.scss
  frontend/src/store/AuthStore.js
  frontend/src/store/AuthStore.test.js
  frontend/src/test-utils/mock.js
  yarn.lock
Labels: feature

#20 Issue 19: fix some errors after merging
  backend/backend/__pycache__/urls.cpython-37.pyc
  backend/db.sqlite3
  backend/requirements.txt
  backend/subroker/__pycache__/admin.cpython-37.pyc
  backend/subroker/__pycache__/models.cpython-37.pyc
  backend/subroker/__pycache__/urls.cpython-37.pyc
  backend/subroker/__pycache__/views.cpython-37.pyc
  backend/subroker/admin.py
  backend/subroker/migrations/0001_initial.py
  backend/subroker/migrations/0002_auto_20211106_0840.py
  backend/subroker/migrations/0002_delete_user.py
  backend/subroker/migrations/0003_group.py
  backend/subroker/migrations/0004_content_review.py
  backend/subroker/migrations/0005_alter_content_user_id.py
  backend/subroker/migrations/0006_alter_group_members.py
  backend/subroker/migrations/__init__.py
  backend/subroker/migrations/__pycache__/0001_initial.cpython-37.pyc
  backend/subroker/migrations/__pycache__/0001_initial.cpython-39.pyc
  backend/subroker/migrations/__pycache__/0002_auto_20211106_0840.cpython-39.pyc
  backend/subroker/migrations/__pycache__/0002_delete_user.cpython-37.pyc
  backend/subroker/migrations/__pycache__/0003_group.cpython-39.pyc
  backend/subroker/migrations/__pycache__/0004_content_review.cpython-39.pyc
  backend/subroker/migrations/__pycache__/0005_alter_content_user_id.cpython-39.pyc
  backend/subroker/migrations/__pycache__/0006_alter_group_members.cpython-39.pyc
  backend/subroker/migrations/__pycache__/__init__.cpython-37.pyc
  backend/subroker/migrations/__pycache__/__init__.cpython-39.pyc
  backend/subroker/views.py
Labels: bug

#22 [Hotfix] apply gitignore not to include unnecessary files
  .gitignore
  backend/backend/__pycache__/__init__.cpython-37.pyc
  backend/backend/__pycache__/settings.cpython-37.pyc
  backend/backend/__pycache__/urls.cpython-37.pyc
  backend/backend/__pycache__/wsgi.cpython-37.pyc
  backend/db.sqlite3
  backend/subroker/__pycache__/__init__.cpython-37.pyc
  backend/subroker/__pycache__/admin.cpython-37.pyc
  backend/subroker/__pycache__/apps.cpython-37.pyc
  backend/subroker/__pycache__/models.cpython-37.pyc
  backend/subroker/__pycache__/urls.cpython-37.pyc
  backend/subroker/__pycache__/views.cpython-37.pyc
Labels: bug, hotfix

#21 [Feature] Implement main page
  frontend/public/images/netflix.png
  frontend/public/images/posters/1.png
  frontend/public/images/posters/10.png
  frontend/public/images/posters/2.png
  frontend/public/images/posters/3.png
  frontend/public/images/posters/4.png
  frontend/public/images/posters/5.png
  frontend/public/images/posters/6.png
  frontend/public/images/posters/7.png
  frontend/public/images/posters/8.png
  frontend/public/images/posters/9.png
  frontend/public/images/tving.png
  frontend/public/images/watcha.png
  frontend/src/base.scss
  frontend/src/components/content/ContentList.js
  frontend/src/components/content/ContentListItem.js
  frontend/src/components/content/ContentSearch.js
  frontend/src/components/group/GroupList.js
  frontend/src/components/group/GroupListItem.js
  frontend/src/components/group/GroupListItem.scss
  frontend/src/components/group/GroupSearch.js
  frontend/src/containers/base/MainPage.js
  frontend/src/containers/base/MainPage.scss
  frontend/src/containers/base/MyPage.js
  frontend/src/store/ContentStore.js
  frontend/src/store/GroupStore.js
Labels: feature

#31 [Test] add test to groupDetailPage
  frontend/src/containers/group/GroupDetailPage.js
  frontend/src/containers/group/GroupDetailPage.test.js
Labels: test

#23 Feature/implement group create page
  frontend/src/containers/group/GroupCreatePage.js
  frontend/src/containers/group/GroupCreatePage.scss
  frontend/src/containers/group/GroupCreatePage.test.js
  frontend/src/containers/group/temp/netflixLogo.png
  frontend/src/containers/group/temp/tvingLogo.png
  frontend/src/containers/group/temp/watchaLogo.png
Labels: enhancement, feature

#40 [Featrue] Add pagination
  frontend/package.json
  frontend/src/components/content/ContentListItem.js
  frontend/src/containers/base/MainPage.js
  frontend/src/containers/base/MainPage.scss
  frontend/src/containers/base/MainPage.test.js
  frontend/yarn.lock
Labels: feature

#44 [Feature] Implement get current user info
  frontend/src/App.js
  frontend/src/store/AuthStore.js
Labels: enhancement, feature

#47 [Feature] Implement recommendation/trending contents
  backend/backend/settings.py
  backend/requirements.txt
  backend/subroker/views.py
  frontend/src/components/content/ContentListItem.js
  frontend/src/containers/base/MainPage.js
  frontend/src/store/ContentStore.js
Labels: feature

#49 Feature/add redux detail,create,mypage
  backend/ott_image/watcha_logo.jpeg
  backend/ott_image/watcha_logo_HSXCsT1.jpeg
  backend/subroker/urls.py
  backend/subroker/views.py
  frontend/.eslintrc.json
  frontend/public/images/coupangplay.png
  frontend/public/images/disney.png
  frontend/public/images/youtube.png
  frontend/src/containers/group/GroupCreatePage.js
  frontend/src/containers/group/GroupDetailPage.js
  frontend/src/containers/group/temp/netflixLogo.png
  frontend/src/containers/group/temp/netflix_macos_bigsur_icon_189917.png
  frontend/src/containers/group/temp/tvingLogo.png
  frontend/src/containers/group/temp/watchaLogo.png
  frontend/src/store/GroupStore.js
  frontend/src/store/OttStore.js
  frontend/src/store/index.js
Labels: feature

#54 [Bug] Fix travis ci error
  .travis.yml
  backend/.pylintrc
  backend/backend/settings.py
  backend/subroker/admin.py
  backend/subroker/migrations/0001_initial.py
  backend/subroker/models.py
  backend/subroker/tests.py
  backend/subroker/urls.py
  backend/subroker/views.py
  frontend/src/components/base/Calendar.js
  frontend/src/components/base/Calendar.test.js
  frontend/src/components/group/GroupListItem.test.js
  frontend/src/components/review/ReviewListItem.js
  frontend/src/containers/auth/LoginPage.test.js
  frontend/src/containers/auth/SignUpPage.test.js
  frontend/src/containers/base/MainPage.js
  frontend/src/containers/base/MainPage.test.js
  frontend/src/containers/base/MyPage.test.js
  frontend/src/containers/group/GroupCreatePage.js
  frontend/src/containers/group/GroupCreatePage.test.js
  frontend/src/containers/group/GroupDetailPage.js
  frontend/src/containers/group/GroupDetailPage.test.js
  frontend/src/store/AuthStore.test.js
  frontend/src/store/ContentStore.test.js
  frontend/src/store/GroupStore.js
  frontend/src/store/GroupStore.test.js
  frontend/src/store/ReviewStore.test.js
  frontend/src/test-utils/mock.js
Labels: bug

#60 [Feature] show group status header
  backend/subroker/tests.py
  backend/subroker/views.py
  frontend/src/App.js
  frontend/src/components/base/NavBar.js
  frontend/src/components/base/NavBar.scss
  frontend/src/components/base/NavBar.test.js
  frontend/src/store/AuthStore.js
Labels: feature
