Repository swsnu/swpp2021-team8, pull requests merged in 2021-12, with the labels that each got.

#63 [Enhancement] Refactor issue #55
  backend/.pylintrc
  backend/subroker/tests.py
  backend/subroker/urls.py
  backend/subroker/views.py
  frontend/src/components/group/GroupListItem.js
  frontend/src/components/group/GroupListItem.test.js
  frontend/src/store/AuthStore.js
  frontend/src/store/ContentStore.js
  frontend/src/store/GroupStore.js
  frontend/src/store/OttStore.js
  frontend/src/store/ReviewStore.js
Labels: enhancement

#69 [Enhancement] Fix Content list item size in MainPage
  frontend/src/components/content/ContentListItem.js
  frontend/src/components/content/ContentListItem.scss
  frontend/src/components/content/ContentListItem.test.js
Labels: enhancement

#79 [Feature] Add search contents List in MainPage
  backend/content/views.py
  frontend/src/containers/base/MainPage.js
  frontend/src/containers/base/MainPage.test.js
Labels: feature

#81 [Feature] Add Django scheduler
  backend/backend/settings.py
  backend/group/management/commands/runapscheduler.py
  backend/ott/models.py
  backend/ott/ott_image/OSI_layer.png
  backend/ott/ott_image/OSI_layer_0rXcjEK.png
  backend/ott/ott_image/lsp-illustration.png
  backend/ott/ott_image/lsp-illustration_gI0Q82q.png
  backend/ott/ott_image/modu-08.jpg
  backend/ott/ott_image/tree_logo.jpg
  backend/public/img/coupangplay.png
  backend/public/img/coupangplay_DPsBsxA.png
  backend/public/img/netflix.png
  backend/public/img/netflix_hMqFm0W.png
  backend/public/img/netflix_hMqFm0W_V2o11pK.png
  backend/public/img/netflix_lrYSLM4.png
  backend/public/img/tving.png
  backend/public/img/tving_Kzfkpfc.png
  backend/public/img/tving_uaruTg2.png
  backend/public/img/watcha.png
  backend/public/img/watcha_MUZ3Kp7.png
  backend/requirements.txt
  frontend/src/components/content/ContentListItem.js
  frontend/src/components/content/ContentListItem.scss
Labels: feature

#85 [Feature] update mypage
  frontend/src/components/base/Calendar.js
  frontend/src/components/base/Calendar.scss
  frontend/src/components/base/Calendar.test.js
  frontend/src/components/content/ContentListItem.js
  frontend/src/components/content/ContentListItem.scss
  frontend/src/components/group/GroupListItem.js
  frontend/src/components/group/GroupListItem.scss
  frontend/src/components/group/GroupListItem.test.js
  frontend/src/containers/base/MainPage.js
  frontend/src/containers/base/MainPage.test.js
  frontend/src/containers/base/MyPage.js
  frontend/src/containers/base/MyPage.scss
  frontend/src/containers/base/MyPage.test.js
Labels: feature

#90 [Enhancement] Fix minor errors before deployment
  backend/.pylintrc
  backend/content/models.py
  backend/content/views.py
  backend/group/tests.py
  frontend/.eslintrc.json
  frontend/.prettierrc
  frontend/src/containers/group/GroupDetailPage.js
  frontend/src/containers/group/GroupEditPage.js
  frontend/src/index.scss
Labels: enhancement

#91 [Deployment] Deployment and update README.md
  README.md
  backend/Dockerfile
  frontend/Dockerfile
  frontend/nginx.conf
Labels: deployment

#104 [Featrue] Test session
  backend/Dockerfile
  backend/backend/settings.py
  backend/content/tests.py
  backend/content/views.py
  backend/group/tests.py
  backend/group/views.py
  backend/review/tests.py
  backend/review/views.py
  backend/user/views.py
  frontend/.eslintrc.json
  frontend/nginx.conf
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/wavve.png
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/base/FilterButton.js
  frontend/src/components/base/Loading.js
  frontend/src/components/base/Loading.scss
  frontend/src/components/content/ContentListItem.js
  frontend/src/components/content/ContentListItem.scss
  frontend/src/components/content/ContentListItem.test.js
  frontend/src/components/group/GroupListItem.js
  frontend/src/components/group/GroupListItem.test.js
  frontend/src/components/review/ReviewList.js
  frontend/src/components/review/ReviewListItem.js
  frontend/src/containers/base/MainPage.js
  frontend/src/containers/base/MainPage.scss
  frontend/src/containers/base/MainPage.test.js
  frontend/src/containers/base/MyPage.js
  frontend/src/containers/base/MyPage.scss
  frontend/src/containers/base/MyPage.test.js
  frontend/src/containers/content/ContentDetailPage.js
  frontend/src/containers/content/ContentDetailPage.scss
  frontend/src/containers/content/ContentDetailPage.test.js
  frontend/src/containers/group/GroupCreatePage.js
  frontend/src/containers/group/GroupDetailPage.js
  frontend/src/containers/group/GroupDetailPage.scss
  frontend/src/containers/group/GroupDetailPage.test.js
  frontend/src/store/ContentStore.js
  frontend/src/store/ContentStore.test.js
  frontend/src/store/ReviewStore.js
  frontend/yarn.lock
Labels: feature

#106 [Feature] Initialize db
  backend/backend/settings.py
  backend/content/migrations/0001_initial.py
  backend/content/migrations/0002_auto_20211207_2126.py
  backend/content/urls.py
  backend/content/views.py
  backend/group/migrations/0001_initial.py
  backend/initialdb.json
  backend/my_settings.py
  backend/ott/migrations/0001_initial.py
  backend/ott/migrations/0002_alter_ott_image.py
  backend/ott/tests.py
  backend/ott/urls.py
  backend/ott/views.py
  backend/review/migrations/0001_initial.py
  backend/secrets.txt
Labels: feature

#109 [Deployment] Apply https
  backend/Dockerfile
  backend/backend/settings.py
  backend/content/tests.py
  frontend/nginx.conf
Labels: deployment

#113 [BugFix] Issue107 bug fix for test session - chiwon
  frontend/package.json
  frontend/src/components/group/GroupListItem.js
  frontend/src/components/group/GroupListItem.test.js
  frontend/src/containers/group/GroupCreatePage.js
  frontend/src/containers/group/GroupCreatePage.scss
  frontend/src/containers/group/GroupCreatePage.test.js
  frontend/src/containers/group/GroupDetailPage.js
  frontend/src/containers/group/GroupDetailPage.scss
  frontend/yarn.lock
Labels: bug

#111 [Bug] Issue 110
  frontend/src/components/base/NavBar.js
  frontend/src/components/base/NavBar.scss
  frontend/src/components/group/GroupListItem.js
  frontend/src/components/group/GroupListItem.test.js
  frontend/src/containers/base/MainPage.scss
Labels: bug

#114 [Feature] Notification
  backend/backend/settings.py
  backend/backend/urls.py
  backend/group/management/commands/runapscheduler.py
  backend/group/views.py
  backend/notification/__init__.py
  backend/notification/admin.py
  backend/notification/apps.py
  backend/notification/migrations/0001_initial.py
  backend/notification/migrations/0002_notification_content.py
  backend/notification/migrations/0003_notification_type.py
  backend/notification/migrations/__init__.py
  backend/notification/models.py
  backend/notification/tests.py
  backend/notification/urls.py
  backend/notification/views.py
  frontend/package.json
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/base/NavBar.js
  frontend/src/components/base/NavBar.scss
  frontend/src/components/base/NavBar.test.js
  frontend/src/store/NotificationStore.js
  frontend/src/store/NotificationStore.test.js
  frontend/src/store/index.js
  frontend/src/test-utils/mock.js
  frontend/yarn.lock
Labels: feature

#116 [Feature] Connect mysql
  backend/Dockerfile
  backend/backend/settings.py
  backend/docker-compose.yml
  backend/my_settings.py
  backend/requirements.txt
Labels: enhancement

#119 Deployment v1.0
  README.md
  backend/content/tests.py
  frontend/src/App.test.js
  frontend/src/components/base/NavBar.test.js
  frontend/src/containers/content/ContentDetailPage.test.js
  frontend/src/containers/group/GroupCreatePage.test.js
  frontend/src/containers/group/GroupDetailPage.js
  frontend/src/containers/group/GroupDetailPage.test.js
  frontend/src/store/OttStore.js
Labels: deployment
